- name: create eth group
  group:
    name: eth
    state: present

- name: create eth user
  user:
    create_home: yes
    comment: beacon-validator user
    home: /home/eth_usr
    name: eth_usr
    group: eth
    state: present

- name: create prometheus user
  user:
    create_home: yes
    comment: prometheus user
    name: prometheus
    group: eth
    state: present

- name: create prometheus user
  user:
    create_home: yes
    comment: prometheus user
    name: prometheus
    group: eth
    state: present

- name: create node_exporter user
  user:
    create_home: yes
    comment: node_exporter user
    name: node_exporter
    group: eth
    state: present
