- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install shasum
  yum:
    name: perl-Digest-SHA
    state: present

- name: Create prysm directory
  file:
    path: /home/eth_usr/prysm
    state: directory
    mode: '0744'
    owner: eth_usr
    group: eth

- name: Download prysm
  get_url:
    url: https://raw.githubusercontent.com/prysmaticlabs/prysm/master/prysm.sh
    dest: /home/eth_usr/prysm/prysm.sh
    mode: '0744'
    owner: eth_usr
    group: eth

- name: Transfer eth-beacon.service
  template:
    src: eth-beacon.service
    dest: /etc/systemd/system/eth-beacon.service
    mode: '0744'
    owner: root
    group: root

- name: Transfer eth-validator.service
  template:
    src: eth-validator.service
    dest: /etc/systemd/system/eth-validator.service
    mode: '0744'
    owner: root
    group: root

- name: Transfer prysm-beacon-service.sh
  template:
    src: prysm-beacon-service.sh
    dest: /opt/prysm-beacon-service.sh
    mode: '0744'
    owner: root
    group: root

- name: Transfer prysm-validator-service.sh
  template:
    src: prysm-validator-service.sh
    dest: /opt/prysm-validator-service.sh
    mode: '0744'
    owner: root
    group: root

- name: Transfer status-check.sh
  template:
    src: status-check.sh
    dest: /opt/status-check.sh
    mode: '0744'
    owner: root
    group: root

- name: Create creds file
  lineinfile:
    dest: /home/eth_usr/prysm/cred
    line: "{{ creds }}"
    regexp: ".*"
    create: yes
    mode: '0640'
    owner: eth_usr
    group: eth

- name: Reload systemd files
  command: systemctl daemon-reload

- name: Enable services
  command: systemctl enable {{ item }}
  with_items:
    - eth-beacon.service
    - eth-validator.service

- name: Generate validator key
  become:
  shell: |
    /home/eth_usr/prysm/
    ./prysm.sh validator accounts create --keystore-path=/prysm/validator --password={{ creds }} > {{ item }}.txt
  with_items:
    - reg_1
    - reg_2
    - reg_3
    - reg_4
